# Generated by Django 5.2.14 on 2026-05-21 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contact_country_code_user_status_activationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='', max_length=120)),
                ('country', models.CharField(default='', max_length=120)),
                ('timezone', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='province',
            name='region',
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=220)),
                ('state_code', models.CharField(default='', max_length=120)),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.state'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
