# Generated by Django 5.2.14 on 2026-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
