"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path 
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o5z$#1m@t%r7^0o^7195ew9)7$$lz_xf-_=jpw*@aaj7s74ttx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.oursaas.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_elasticsearch_dsl', 
    'drf_spectacular',
    'drf_spectacular_sidecar', 
    'rest_framework_simplejwt.token_blacklist',
    
    # Local apps
    'accounts',
    'shops',
    'products',
    'orders',
    'merchants',
    'utils',
    'config'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.LoggingMiddleware', 
    'config.middleware.ResponseHandler',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "../templates"),
        ], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "init_command": "PRAGMA synchronous=3; PRAGMA cache_size=2000;",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/+

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'static_cdn')
MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=3),
    'JWT_ALLOW_REFRESH': True,
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ), 
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.CustomJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.CustomPagination',
    'PAGE_SIZE': 10,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'config.exception.custom_exception_handler'
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': 'http://localhost:9200',
        'timeout': 1.0,
        'max_retries': 0,
    },
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'BlazePay API',
    'DESCRIPTION': 'Core API business management and services. ',
    'CONTACT': {},
    'LICENSE': {},
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'EXTERNAL_DOCS': {},
    'EXTENSIONS_INFO': {},
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVE_AUTHENTICATION': [
        'accounts.authentication.CustomJWTAuthentication',
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    'SWAGGER_UI_DIST': 'SIDECAR',  # shorthand to use the sidecar instead
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE': True,
    'CAMELIZE_NAMES': False,

    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuthTraxion': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'name': 'Authorization',
                'in': 'header'
            },
        },
    },
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
    ],
    'SORT_OPERATIONS': False,
    'SORT_OPERATION_PARAMETERS': False,
    'COMPONENT_SPLIT_REQUEST': True,
    # OTHER SETTINGS
}
APPEND_SLASH = False


# ----------- Configs ------------------
CORS_ALLOW_ALL_ORIGINS = False
BASE_URL = "http://127.0.0.1:8000/"
ACCESS_TOKEN_EXPIRATION_MINUTES = 1440 # 1 day
REFRESH_TOKEN_EXPIRATION_MINUTES = 18720 # 13 days
PROJECT_ENVIRONMENT = 'dev'
CACHE_REQUEST_TIMEOUT_SECONDS = 120
REDIS_LOCATION = "redis://redis:6379/1"
SOCIAL_SECRET = 'xxxxxxxxxzxxxx'
API_SECRET_KEY = 'x'


CACHE_MIDDLEWARE_SECONDS = CACHE_REQUEST_TIMEOUT_SECONDS
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        'TIMEOUT': int(CACHE_REQUEST_TIMEOUT_SECONDS), # Cache timeout in seconds (e.g., 300 seconds = 5 minutes)
    }
}

try:
    from config.local import *
except:
    pass


LOGGING = { 
    'version': 1,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
        'custom':{
            'format':"API [%(levelname)s] %(asctime)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
        },
    }, 
    'handlers': {
        'logging_handler':{
            'class':'config.logger.CustomFileHandler',
            'level': 'WARNING' if PROJECT_ENVIRONMENT == 'production' else 'DEBUG',
            'formatter': 'custom',
            'maxBytes': 31457280,  # 1024 * 1024 * 30B = 30MB
            'backupCount': 5,
            'filename':'logs/api.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'custom'
        },  
    },
    'loggers': {
        'django': {
            'handlers': ['logging_handler', 'console'],
            'level': 'WARNING' if PROJECT_ENVIRONMENT == 'production' else 'DEBUG',
            'propagate': True,
        },
        'django.db.backends': { 
            'handlers': ['console'],
            'level': 'WARNING',   # DEBUG will log all queries, so change it to WARNING.
            'propagate': False,   # Don't propagate to other handlers
        },
        'django.utils.autoreload': {
            'handlers': ['console'],
            'level': 'WARNING',   # DEBUG will log all queries, so change it to WARNING.
            'propagate': False,   # Don't propagate to other handlers
        },
        'django.template': {
            'handlers': ['console'],
            'level': 'WARNING',   # DEBUG will log all queries, so change it to WARNING.
            'propagate': False,   # Don't propagate to other handlers
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',   # DEBUG will log all queries, so change it to WARNING.
            'propagate': False,   # Don't propagate to other handlers
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',   # DEBUG will log all queries, so change it to WARNING.
            'propagate': False,   # Don't propagate to other handlers
        }, 
    }
}
