# Generated by Django 5.2.14 on 2026-05-21 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.IntegerField(choices=[(0, ''), (1, 'Initial Registration')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approve'), (-1, 'Rejected'), (2, 'Draft')], default=0)),
                ('event', models.IntegerField(choices=[(0, 'New'), (1, 'Update'), (1, 'Delete')], default=0)),
                ('search', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('current_details', models.TextField(blank=True, default='', null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('new_details', models.TextField(blank=True, default='', null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
